version: '3.7'
services:
  mongo1:
    image: mongo:6.0
    container_name: mongo1
    command: --replSet rs0 --bind_ip_all
    ports:
      - 27017:27017
    volumes:
      - mongo1-data:/data/db
    networks:
      - mongonet

  mongo2:
    image: mongo:6.0
    container_name: mongo2
    command: --replSet rs0 --bind_ip_all
    ports:
      - 27018:27017
    volumes:
      - mongo2-data:/data/db
    networks:
      - mongonet

  mongo3:
    image: mongo:6.0
    container_name: mongo3
    command: --replSet rs0 --bind_ip_all
    ports:
      - 27019:27017
    volumes:
      - mongo3-data:/data/db
    networks:
      - mongonet

networks:
  mongonet:
      driver: bridge


volumes:
  mongo1-data:
  mongo2-data:
  mongo3-data:
